// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeliGiderAnaliziClassLib.Migrations
{
    [DbContext(typeof(GelirGiderAnaliziContext))]
    partial class GelirGiderAnaliziContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GelirGiderAnalizi.Models.GiderIslModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("EvrakNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("GiderId")
                        .HasColumnType("int");

                    b.Property<int?>("KasaId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeDurumu")
                        .HasColumnType("longtext");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("longtext");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Turu")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GiderIslModels");
                });

            modelBuilder.Entity("GelirGiderAnalizi.Models.GiderModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AboneNo")
                        .HasColumnType("longtext");

                    b.Property<string>("GiderAciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("GiderAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("GiderKategori")
                        .HasColumnType("longtext");

                    b.Property<string>("GiderKodu")
                        .HasColumnType("longtext");

                    b.Property<string>("GiderTuru")
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GiderModels");
                });

            modelBuilder.Entity("GelirGiderAnalizi.Models.LoginModel", b =>
                {
                    b.Property<string>("ApiKullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("ApiKullaniciSifre")
                        .HasColumnType("longtext");

                    b.Property<string>("DonemYil")
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("longtext");

                    b.Property<string>("KullaniciSifre")
                        .HasColumnType("longtext");

                    b.Property<string>("SubeAd")
                        .HasColumnType("longtext");

                    b.Property<string>("VergiNumarasi")
                        .HasColumnType("longtext");

                    b.Property<string>("VeritabaniAd")
                        .HasColumnType("longtext");

                    b.ToTable("LoginModels");
                });
#pragma warning restore 612, 618
        }
    }
}
